// Even Fibonacci Numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, 
// find the sum of the even-valued terms.

function fiboEvenSum(n) {
    if (n <= 3) {
        return;
    }

    let num1 = 1;
    let num2 = 2;
    let next = num1 + num2;
    let sum_even_nums = 0;

    while (next < n) {
        num1 = num2;
        num2 = next;
        next = num1 + num2;

        if (num1 % 2 === 0) {
            sum_even_nums += num1;
        }
    }

    if (num2 % 2 === 0) {
        sum_even_nums += num2;
    }

    if (next % 2 === 0) {
        sum_even_nums += next;
    }

    return sum_even_nums;
}